### PR TITLE
Add shellcheck to the Travis run

### PR DESCRIPTION
**Pull request by edmorley**
Since it can help prevent a variety of bugs due to bash quirks:
https://github.com/koalaman/shellcheck#gallery-of-bad-code

### CODE REVIEW

**Comment by kennethreitz** [comment]
is there a ppa?

**Comment by edmorley** [comment]
There is:
https://github.com/koalaman/shellcheck#travis-ci-setup
...however it means the version can change under us, causing new lint failures. (There's also a `latest` version of the archive download too.)

Though I guess that's both good and bad, in that it's less hassle to keep up to date.

**Comment by edmorley** [comment]
PR updated with the shellcheck suggested fixes, so shellcheck now exits zero.

@dzuelke would you mind taking a look here too?

**Comment by edmorley** [comment]
Oh and make sure to view one commit at a time - clearer diff and the commit message links to the rationale.

**Comment by kennethreitz** [comment]
This looks good to me! Looking forward to seeing if @dzuelke has any thoughts.

**Comment by kennethreitz** [comment]
I approve. Got shellcheck running in sublime locally. Learning a lot.

**Pull request merged**
