### PR TITLE
Added export-env function and helper functions

### PR DESCRIPTION
**Pull request by jkutner**
**DO NOT MERGE**

This PR is a conversation piece :) I want to add an `export-env` function, but I also made some changes to the `sub-env` function to reduce duplication. In refactoring, I identified some concerns:

* The `sub-env` function expects that the `ENV_DIR` env var to be set. I think this is a significant design decision  (which I'm not against but want to make sure it's clear). Will this stdlib favor convention, or will it require that all values be passed explicitly as args? For example, it could also use the `CACHE_DIR` env var by convention when I add a `cache-copy` function.
* In the `export-env` function, I've favored the most common case. Buildpacks that have unusual an regex for blacklisting will probably need to implement this function on their own. However, I could not find an example of this in any of our official buildpacks. I think we should prefer this kind of approach.
* Then `env-blacklist` function could be "private" (potentially prefixing it with an `_` to denote this). Do we want to adopt a pattern like that? I have mixed feelings.
* There are no tests. I can't be confident in merging this change to `sub-env`. I'm not sure how it's used.

### CODE REVIEW

**Comment by kennethreitz** [comment]
It really depends on the situation, whether to use environment variables or not. Asking to standardize on one vs the other is like asking someone to always used keyword arguments, vs positional arguments. Sometimes, both are approprirate, especially considering the codestyle of the entire codebase. 

So, based on this codebase, having expected Environment Variables is expected, but only for *configuration* -- arguments are still very appropriate at certain times. 

------

e.g. I think your call to make `sub-env` require an `ENV_DIR` env var is appropriate.

**Comment by jkutner** [comment]
That's true. But maybe we can standardize on the vars that come into the buildpack as args (`BUILD_DIR`, `CACHE_DIR`, `ENV_DIR`). We could have a mandate that these will never be passed as args, and strictly used as named vars. Thoughts? I'm mostly interested in consistency.

**Comment by kennethreitz** [comment]
I don't see this codebase growing much at all, so I see no need to make such decisions, I suppose. I think it's pretty much complete.

**Comment by kennethreitz** [comment]
README needs to be updated with new functions.

**Comment by kennethreitz** [comment]
In general, I think we should be trying to limit the number of functions to be as small as possible. So, while I appreciate the refactor, I'm not in favor of it.

Unless, as you suggested, we adopt `_` to denote undocumented private APIs. Then, I'm +100. So, let's make that change.

**Comment by kennethreitz** [comment]
Updated.

**Comment by kennethreitz** [comment]
Made export-env public. Documented it. Now, to test it...

**Comment by kennethreitz** [comment]
All set! Once tests pass, merging.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
deployed v3

**Comment by jkutner** [comment]
@kennethreitz thanks!

**Pull request merged**
